version: '3.7'

services:
  database:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: shop
    ports:
      - '${DATABASE_PORT}:5432'
    container_name: online_shop_database